# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydronote', '0004_auto_20170319_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
