# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydronote', '0005_note_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='session_key',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
