# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydronote', '0006_auto_20170401_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
