# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydronote', '0008_note_sort_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(),
        ),
    ]
